import { expect, test } from '@playwright/test'

test('data table renders accessibly and preserves stable row identity', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/data-table-test')
  await expect(page.getByRole('table')).toBeVisible()
  await expect(page.getByRole('row')).toHaveCount(3)
  await expect(page.getByRole('button', { name: 'Next' })).toBeEnabled()
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByRole('row')).toHaveCount(2)
  await expect(page.getByRole('button', { name: 'Next' })).toBeDisabled()
  await page.getByRole('combobox', { name: 'Rows per page' }).selectOption('25')
  await expect(page.getByRole('row')).toHaveCount(4)
  await page.getByRole('textbox', { name: 'Filter rows' }).fill('Alpha')
  await expect(page.getByRole('cell', { name: 'Beta' })).toHaveCount(0)
  await page.getByRole('checkbox', { name: 'name column' }).uncheck()
  await expect(page.getByRole('columnheader', { name: 'Name' })).toHaveCount(0)
  await page.getByRole('checkbox', { name: 'Show name column' }).check()
  await expect(page.getByRole('columnheader', { name: 'Name' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Filter rows' }).fill('')
  await page.getByRole('checkbox', { name: 'Select row a' }).check()
  await expect(page.getByRole('checkbox', { name: 'Select row a' })).toBeChecked()
  await page.getByRole('combobox', { name: 'Rows per page' }).selectOption('25')
  await page.getByTestId('replace').click()
  await expect(page.getByRole('checkbox', { name: 'Select row a' })).toBeChecked()
  const sort = page.getByRole('button', { name: 'Sort by Name' })
  await sort.focus(); await page.keyboard.press('Enter')
  await expect(page.getByRole('cell').nth(0)).toHaveText('Alpha')
  await sort.click()
  await expect(page.getByRole('cell').nth(0)).toHaveText('Gamma')
  await page.getByTestId('replace').click()
  await expect(page.getByRole('cell', { name: 'Alpha' })).toBeVisible()
  await page.getByTestId('loading').click(); await expect(page.getByRole('status')).toContainText('Loading')
  await page.getByTestId('loading').click(); await page.getByTestId('error').click(); await expect(page.getByRole('alert')).toContainText('Unable')
  expect(errors).toEqual([])
})
