<script setup lang="ts">
import { toast } from 'vue-sonner'; import { IconPlus, IconTrash, IconPencil } from '@tabler/icons-vue'
definePageMeta({ middleware:'auth', layout:'app' }); useHead({ title:'Projects' })
type Project={id:string,name:string,description:string|null,createdAt:string,updatedAt:string}
const { data:projects, status, error, refresh } = await useFetch<Project[]>('/api/projects', { default:()=>[] })
const editing=ref<Project|null>(null); const name=ref(''); const description=ref(''); const busy=ref(false)
function edit(p?:Project){ editing.value=p??null; name.value=p?.name??''; description.value=p?.description??'' }
async function save(){ busy.value=true; try { if(editing.value) await $fetch(`/api/projects/${editing.value.id}`,{method:'PATCH',body:{name:name.value,description:description.value}}); else await $fetch('/api/projects',{method:'POST',body:{name:name.value,description:description.value}}); toast.success(editing.value?'Project updated':'Project created'); edit(); await refresh() } catch{ toast.error('Could not save project') } finally{busy.value=false} }
async function remove(p:Project){ if(!confirm(`Delete ${p.name}?`)) return; try { await $fetch(`/api/projects/${p.id}`,{method:'DELETE'}); toast.success('Project deleted'); await refresh() } catch{toast.error('Could not delete project')} }
</script>
<template><div class="space-y-6"><div class="flex items-center justify-between"><div><h1 class="text-3xl font-bold">Projects</h1><p class="text-[var(--muted)]">Your authenticated, owner-scoped workspace.</p></div><button class="btn" @click="edit()"><IconPlus :size="18" />New project</button></div><p v-if="status==='pending'">Loading projects…</p><div v-else-if="error" class="card" role="alert">Projects could not be loaded. <button class="underline" @click="() => refresh()">Try again</button></div><div v-else-if="!projects.length" class="card py-14 text-center"><h2 class="font-semibold">No projects yet</h2><p class="text-[var(--muted)]">Create one to prove the full stack is working.</p></div><div v-else class="grid gap-3 sm:grid-cols-2"><article v-for="p in projects" :key="p.id" class="card"><h2 class="font-semibold">{{p.name}}</h2><p class="min-h-12 text-sm text-[var(--muted)]">{{p.description||'No description'}}</p><div class="mt-4 flex gap-2"><button class="btn btn-secondary" @click="edit(p)"><IconPencil :size="16" />Edit</button><button class="btn btn-secondary" @click="remove(p)"><IconTrash :size="16" />Delete</button></div></article></div><form class="card space-y-3" @submit.prevent="save"><h2 class="font-semibold">{{editing?'Edit project':'Create project'}}</h2><label class="block">Name<input v-model="name" class="field mt-1" minlength="1" maxlength="120" required></label><label class="block">Description<textarea v-model="description" class="field mt-1" maxlength="1000" rows="3" /></label><div class="flex gap-2"><button class="btn" :disabled="busy">{{busy?'Saving…':'Save project'}}</button><button v-if="editing" type="button" class="btn btn-secondary" @click="edit()">Cancel</button></div></form></div></template>
