import { boolean, index, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

export const apikey = pgTable('apikey', {
  id: text('id').primaryKey(),
  configId: text('config_id').default('default').notNull(),
  name: text('name'),
  start: text('start'),
  prefix: text('prefix'),
  key: text('key').notNull(),
  referenceId: text('reference_id').notNull(),
  refillInterval: integer('refill_interval'),
  refillAmount: integer('refill_amount'),
  lastRefillAt: timestamp('last_refill_at', { withTimezone: true }),
  enabled: boolean('enabled').default(true).notNull(),
  rateLimitEnabled: boolean('rate_limit_enabled').default(true).notNull(),
  rateLimitTimeWindow: integer('rate_limit_time_window'),
  rateLimitMax: integer('rate_limit_max'),
  requestCount: integer('request_count').default(0).notNull(),
  remaining: integer('remaining'),
  lastRequest: timestamp('last_request', { withTimezone: true }),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  permissions: text('permissions'),
  metadata: text('metadata'),
}, table => [
  index('apikey_config_id_idx').on(table.configId),
  index('apikey_reference_id_idx').on(table.referenceId),
  index('apikey_key_idx').on(table.key),
])
