/** Provision a Pocket ID OIDC client through its versioned admin API. */
import { appendFile } from 'node:fs/promises'
type Client={id:string,name:string,clientId:string,clientSecret?:string}; type ClientList=Client[]|{data:Client[]}
const admin=process.env.DEV_OIDC_ADMIN_URL?.replace(/\/$/,''); const token=process.env.DEV_OIDC_API_KEY; const base=process.env.APP_BASE_URL?.replace(/\/$/,'')||'http://localhost:3000'
if(!admin||!token){console.error('Missing DEV_OIDC_ADMIN_URL or DEV_OIDC_API_KEY. Set both to provision Pocket ID; GitHub OAuth does not require them.');process.exit(2)}
const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'}; const name='Nuxt full-stack starter'; const redirect=[`${base}/api/auth/oauth2/callback/oidc`]; const logout=[base]
async function request<T>(path:string,init?:RequestInit):Promise<T>{let r:Response;try{r=await fetch(`${admin}${path}`,{...init,headers:{...headers,...init?.headers}})}catch(error){throw new Error(`Pocket ID is unavailable at ${admin}`,{cause:error})}if(!r.ok)throw new Error(`Pocket ID API ${path} returned ${r.status}: ${await r.text()}`);return (r.status===204?null:await r.json()) as T}
try {
  // Pocket ID v2 exposes API-key authenticated OIDC client administration here.
  const list=await request<ClientList>('/api/oidc/clients'); const existing=(Array.isArray(list)?list:list.data).find(client=>client.name===name)
  const body={name,callbackURLs:redirect,logoutCallbackURLs:logout,isPublic:false,pkceEnabled:true}
  const client=existing?await request<Client>(`/api/oidc/clients/${existing.id}`,{method:'PUT',body:JSON.stringify(body)}):await request<Client>('/api/oidc/clients',{method:'POST',body:JSON.stringify(body)})
  const secret=client.clientSecret??existing?.clientSecret; if(!secret) throw new Error('Pocket ID did not return a client secret. Rotate/create one in the admin UI and rerun.')
  const values=`\n# Generated by bun run auth:provision\nNUXT_OIDC_ISSUER=${admin}\nNUXT_OIDC_CLIENT_ID=${client.clientId}\nNUXT_OIDC_CLIENT_SECRET=${secret}\n`
  await appendFile('.env.local',values,{mode:0o600}); console.log(`Provisioned ${client.clientId}; credentials appended to ignored .env.local`)
} catch(e){console.error(e instanceof Error?e.message:e);process.exit(1)}
