<script setup lang="ts" generic="TData extends Record<string, unknown>">
import { FlexRender, stockFeatures, useTable, type ColumnDef, type ColumnFiltersState, type PaginationState, type RowSelectionState, type SortingState, type VisibilityState } from '@tanstack/vue-table'
import { computed, ref, watch } from 'vue'
const props = withDefaults(defineProps<{ data: TData[]; columns: ColumnDef<any, TData, any>[]; rowId?: (row: TData, index: number) => string; sorting?: SortingState; columnFilters?: ColumnFiltersState; pagination?: PaginationState; columnVisibility?: VisibilityState; rowSelection?: RowSelectionState; manualSorting?: boolean; manualFiltering?: boolean; manualPagination?: boolean; pageCount?: number; enableRowSelection?: boolean; pageSizeOptions?: number[] }>(), { sorting: () => [], columnFilters: () => [], pagination: () => ({ pageIndex: 0, pageSize: 10 }), columnVisibility: () => ({}), rowSelection: () => ({}), pageSizeOptions: () => [10, 25, 50] })
const emit = defineEmits<{ 'update:sorting': [SortingState]; 'update:columnFilters': [ColumnFiltersState]; 'update:pagination': [PaginationState]; 'update:columnVisibility': [VisibilityState]; 'update:rowSelection': [RowSelectionState] }>()
const sorting = ref(props.sorting), columnFilters = ref(props.columnFilters), pagination = ref(props.pagination), columnVisibility = ref(props.columnVisibility), rowSelection = ref(props.rowSelection)
watch(() => props.sorting, value => { sorting.value = value }); watch(() => props.columnFilters, value => { columnFilters.value = value }); watch(() => props.pagination, value => { pagination.value = value }); watch(() => props.columnVisibility, value => { columnVisibility.value = value }); watch(() => props.rowSelection, value => { rowSelection.value = value })
const table = useTable({ features: stockFeatures, data: computed(() => props.data), columns: computed(() => props.columns) as any, getRowId: props.rowId as any, state: computed(() => ({ sorting: sorting.value, columnFilters: columnFilters.value, pagination: pagination.value, columnVisibility: columnVisibility.value, rowSelection: rowSelection.value })) as any, manualSorting: props.manualSorting, manualFiltering: props.manualFiltering, manualPagination: props.manualPagination, pageCount: props.pageCount, enableRowSelection: props.enableRowSelection, onSortingChange: (updater: any) => { sorting.value = typeof updater === 'function' ? updater(sorting.value) : updater; emit('update:sorting', sorting.value) }, onColumnFiltersChange: (updater: any) => { columnFilters.value = typeof updater === 'function' ? updater(columnFilters.value) : updater; emit('update:columnFilters', columnFilters.value) }, onPaginationChange: (updater: any) => { pagination.value = typeof updater === 'function' ? updater(pagination.value) : updater; emit('update:pagination', pagination.value) }, onColumnVisibilityChange: (updater: any) => { columnVisibility.value = typeof updater === 'function' ? updater(columnVisibility.value) : updater; emit('update:columnVisibility', columnVisibility.value) }, onRowSelectionChange: (updater: any) => { rowSelection.value = typeof updater === 'function' ? updater(rowSelection.value) : updater; emit('update:rowSelection', rowSelection.value) } }) as any
const rows = computed(() => table.getRowModel().rows)
function sort(column: any) { column.toggleSorting(column.getIsSorted() === 'asc') }
</script>
<template>
  <div class="data-table" role="region" aria-label="Data table" tabindex="0"><table><thead><tr v-for="group in table.getHeaderGroups()" :key="group.id"><th v-for="header in group.headers" :key="header.id" scope="col"><button v-if="!header.isPlaceholder && header.column.getCanSort?.()" type="button" :aria-label="`Sort by ${String(header.column.columnDef.header ?? header.id)}`" @click="sort(header.column)"><FlexRender :header="header" /><span aria-hidden="true">{{ header.column.getIsSorted?.() === 'asc' ? ' ↑' : header.column.getIsSorted?.() === 'desc' ? ' ↓' : '' }}</span></button><FlexRender v-else-if="!header.isPlaceholder" :header="header" /></th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td v-for="cell in row.getVisibleCells()" :key="cell.id"><FlexRender :cell="cell" /></td></tr><tr v-if="rows.length === 0"><td :colspan="table.getVisibleLeafColumns().length">No results</td></tr></tbody></table><nav aria-label="Table pagination"><button type="button" :disabled="!table.getCanPreviousPage?.()" @click="table.previousPage?.()">Previous</button><span aria-live="polite">Page {{ (table.getState().pagination?.pageIndex ?? 0) + 1 }}</span><button type="button" :disabled="!table.getCanNextPage?.()" @click="table.nextPage?.()">Next</button><label>Rows <select :value="table.getState().pagination?.pageSize ?? 10" @change="table.setPageSize?.(Number(($event.target as HTMLSelectElement).value))"><option v-for="size in pageSizeOptions" :key="size" :value="size">{{ size }}</option></select></label></nav></div>
</template>
