import { and, desc, eq, inArray, lt, or, sql } from 'drizzle-orm'
import { PgTransaction, type PgDatabase, type PgQueryResultHKT } from 'drizzle-orm/pg-core'
import { flagDefinition, flagOverride } from './schema'
import { FeatureFlagsError, safeFeatureFlagsError } from './errors'
import { context, fields, key, opaqueId, pagination, revision, target, type FlagContext } from './validation'
import { rolloutBucket } from './bucket'
export type FlagsConnection = Pick<PgDatabase<PgQueryResultHKT>, 'select'|'insert'|'update'|'delete'|'execute'>
export interface FlagsDatabase { transaction<T>(operation:(tx:FlagsConnection)=>Promise<T>):Promise<T> }
export interface FlagDetails { value:boolean, reason:'not-found'|'disabled'|'tenant-target'|'user-target'|'rollout'|'default'|'error', revision?:number, errorCode?:FeatureFlagsError['code'] }
export interface FlagManagementActor { readonly userId:string }
export interface FlagsOptions { managementGuard?:(actor:FlagManagementActor,operation:'create'|'update'|'override'|'list',tx:FlagsConnection)=>Promise<boolean>, onChange?:(tx:FlagsConnection,operation:'flags.create'|'flags.update'|'flags.override',definition:typeof flagDefinition.$inferSelect)=>Promise<void> }
async function bounds(tx:FlagsConnection, evaluation=false) { if(!(tx instanceof PgTransaction))throw new FeatureFlagsError('invalid-input'); await tx.execute(sql`SELECT set_config('statement_timeout',${evaluation?'1000':'5000'},true),set_config('lock_timeout','2000',true)`) }
function validDefinition(row:typeof flagDefinition.$inferSelect) { try { key(row.key); fields({description:row.description,enabled:row.enabled,defaultValue:row.defaultValue,rolloutBasisPoints:row.rolloutBasisPoints}); revision(row.revision); return true } catch { return false } }
function checkedKeys(input:readonly string[]) { if(!Array.isArray(input)||input.length>50||new Set(input).size!==input.length)throw new FeatureFlagsError('invalid-input'); return input.map(key) }
export function defineFeatureFlags(options:FlagsOptions={}) {
  if(Object.values(options).some(callback=>callback!==undefined&&typeof callback!=='function'))throw new FeatureFlagsError('configuration')
  async function evaluateManyTx(tx:FlagsConnection,input:readonly string[],rawContext:FlagContext={}) {
    const keys=checkedKeys(input), ctx=context(rawContext)
    const results:Record<string,FlagDetails>=Object.fromEntries(keys.map(k=>[k,{value:false,reason:'not-found'}]))
    if(!keys.length)return results
    try {
      await bounds(tx,true)
      // One bounded SQL snapshot reads every definition and relevant exact override.
      const match=or(ctx.tenantId===undefined?undefined:and(eq(flagOverride.targetKind,'tenant'),eq(flagOverride.targetId,ctx.tenantId)),ctx.userId===undefined?undefined:and(eq(flagOverride.targetKind,'user'),eq(flagOverride.targetId,ctx.userId)))
      const rows=await tx.select({definition:flagDefinition,override:flagOverride}).from(flagDefinition).leftJoin(flagOverride,and(eq(flagDefinition.key,flagOverride.flagKey),match??sql`false`)).where(inArray(flagDefinition.key,keys))
      const grouped=new Map<string,{definition:typeof flagDefinition.$inferSelect,overrides:(typeof flagOverride.$inferSelect)[]}>()
      for(const row of rows){const existing=grouped.get(row.definition.key)??{definition:row.definition,overrides:[]}; if(row.override)existing.overrides.push(row.override);grouped.set(row.definition.key,existing)}
      for(const [k,{definition:d,overrides}] of grouped){
        if(!validDefinition(d)||overrides.some(o=>!['user','tenant'].includes(o.targetKind)||typeof o.value!=='boolean')){results[k]={value:false,reason:'error',errorCode:'configuration'};continue}
        const base={revision:d.revision}
        if(!d.enabled){results[k]={...base,value:false,reason:'disabled'};continue}
        const tenant=overrides.find(o=>o.targetKind==='tenant'&&o.targetId===ctx.tenantId),user=overrides.find(o=>o.targetKind==='user'&&o.targetId===ctx.userId)
        if(tenant){results[k]={...base,value:tenant.value,reason:'tenant-target'};continue}
        if(user){results[k]={...base,value:user.value,reason:'user-target'};continue}
        const identity=ctx.tenantId??ctx.userId
        if(d.rolloutBasisPoints!==null&&identity!==undefined){results[k]={...base,value:rolloutBucket(k,ctx.tenantId===undefined?'user':'tenant',identity)<d.rolloutBasisPoints,reason:'rollout'};continue}
        results[k]={...base,value:d.defaultValue,reason:'default'}
      }
      return results
    } catch(error){const safe=safeFeatureFlagsError(error);return Object.fromEntries(keys.map(k=>[k,{value:false,reason:'error',errorCode:safe.code}])) as Record<string,FlagDetails>}
  }
  async function evaluateMany(db:FlagsDatabase,input:readonly string[],ctx:FlagContext={}) {const keys=checkedKeys(input),trusted=context(ctx);try{return await db.transaction(tx=>evaluateManyTx(tx,keys,trusted))}catch(error){const safe=safeFeatureFlagsError(error);return Object.fromEntries(keys.map(k=>[k,{value:false,reason:'error',errorCode:safe.code}])) as Record<string,FlagDetails>}}
  async function evaluateBooleanDetails(db:FlagsDatabase,input:string,ctx:FlagContext={}){const k=key(input);return (await evaluateMany(db,[k],ctx))[k]!}
  async function evaluateBoolean(db:FlagsDatabase,input:string,ctx:FlagContext={}){return (await evaluateBooleanDetails(db,input,ctx)).value}
  function preflight(actor:FlagManagementActor){if(!actor?.userId)throw new FeatureFlagsError('unauthenticated');opaqueId(actor.userId);if(!options.managementGuard)throw new FeatureFlagsError('forbidden')}
  async function guard(tx:FlagsConnection,actor:FlagManagementActor,operation:'create'|'update'|'override'|'list'){preflight(actor);await bounds(tx);if(!await options.managementGuard!(Object.freeze({userId:actor.userId}),operation,tx))throw new FeatureFlagsError('forbidden')}
  async function locked(tx:FlagsConnection,k:string,expected:number){const [row]=await tx.select().from(flagDefinition).where(eq(flagDefinition.key,k)).limit(1).for('update');if(!row)throw new FeatureFlagsError('not-found');if(!validDefinition(row))throw new FeatureFlagsError('configuration');if(row.revision!==expected)throw new FeatureFlagsError('conflict');return row}
  async function changed(tx:FlagsConnection,current:typeof flagDefinition.$inferSelect,operation:'flags.update'|'flags.override',patch:ReturnType<typeof fields>={}){if(current.revision>=2147483647)throw new FeatureFlagsError('conflict');const [row]=await tx.update(flagDefinition).set({...patch,revision:current.revision+1,updatedAt:new Date()}).where(eq(flagDefinition.key,current.key)).returning();if(options.onChange)await options.onChange(tx,operation,row!);return row!}
  async function createDefinitionTx(tx:FlagsConnection,actor:FlagManagementActor,rawKey:string,input:Record<string,unknown>={}){const k=key(rawKey),patch=fields(input,true);try{await guard(tx,actor,'create');const [row]=await tx.insert(flagDefinition).values({key:k,...patch}).onConflictDoNothing().returning();if(!row)throw new FeatureFlagsError('conflict');if(options.onChange)await options.onChange(tx,'flags.create',row);return {definition:row,changed:true}}catch(error){throw safeFeatureFlagsError(error)}}
  async function updateDefinitionTx(tx:FlagsConnection,actor:FlagManagementActor,rawKey:string,expectedRevision:number,input:Record<string,unknown>){const k=key(rawKey),expected=revision(expectedRevision),patch=fields(input);try{await guard(tx,actor,'update');const current=await locked(tx,k,expected);if(Object.entries(patch).every(([field,value])=>current[field as keyof typeof current]===value))return {definition:current,changed:false};return {definition:await changed(tx,current,'flags.update',patch),changed:true}}catch(error){throw safeFeatureFlagsError(error)}}
  async function overrideTx(tx:FlagsConnection,actor:FlagManagementActor,rawKey:string,expectedRevision:number,rawTarget:{targetKind:'user'|'tenant',targetId:string},value:boolean|undefined){const k=key(rawKey),expected=revision(expectedRevision),t=target(rawTarget);if(value!==undefined&&typeof value!=='boolean')throw new FeatureFlagsError('invalid-input');try{await guard(tx,actor,'override');const current=await locked(tx,k,expected);const predicate=and(eq(flagOverride.flagKey,k),eq(flagOverride.targetKind,t.targetKind),eq(flagOverride.targetId,t.targetId));const [old]=await tx.select().from(flagOverride).where(predicate).limit(1);if(value===undefined?!old:old?.value===value)return {definition:current,changed:false};if(value===undefined)await tx.delete(flagOverride).where(predicate);else await tx.insert(flagOverride).values({flagKey:k,...t,value}).onConflictDoUpdate({target:[flagOverride.flagKey,flagOverride.targetKind,flagOverride.targetId],set:{value}});return {definition:await changed(tx,current,'flags.override'),changed:true}}catch(error){throw safeFeatureFlagsError(error)}}
  async function createDefinition(db:FlagsDatabase,actor:FlagManagementActor,k:string,input:Record<string,unknown>={}){preflight(actor);key(k);fields(input,true);try{return await db.transaction(tx=>createDefinitionTx(tx,actor,k,input))}catch(error){throw safeFeatureFlagsError(error)}}
  async function updateDefinition(db:FlagsDatabase,actor:FlagManagementActor,k:string,expected:number,input:Record<string,unknown>){preflight(actor);key(k);revision(expected);fields(input);try{return await db.transaction(tx=>updateDefinitionTx(tx,actor,k,expected,input))}catch(error){throw safeFeatureFlagsError(error)}}
  async function setOverride(db:FlagsDatabase,actor:FlagManagementActor,k:string,expected:number,t:{targetKind:'user'|'tenant',targetId:string},value:boolean){preflight(actor);key(k);revision(expected);target(t);if(typeof value!=='boolean')throw new FeatureFlagsError('invalid-input');try{return await db.transaction(tx=>overrideTx(tx,actor,k,expected,t,value))}catch(error){throw safeFeatureFlagsError(error)}}
  async function removeOverride(db:FlagsDatabase,actor:FlagManagementActor,k:string,expected:number,t:{targetKind:'user'|'tenant',targetId:string}){preflight(actor);key(k);revision(expected);target(t);try{return await db.transaction(tx=>overrideTx(tx,actor,k,expected,t,undefined))}catch(error){throw safeFeatureFlagsError(error)}}
  async function listDefinitions(db:FlagsDatabase,actor:FlagManagementActor,input:{limit?:number,cursor?:string}={}){preflight(actor);const{limit,tuple}=pagination(input);try{return await db.transaction(async tx=>{await guard(tx,actor,'list');const rows=await tx.select().from(flagDefinition).where(tuple?or(lt(flagDefinition.createdAt,new Date(tuple[1])),and(eq(flagDefinition.createdAt,new Date(tuple[1])),lt(flagDefinition.key,tuple[2]))):undefined).orderBy(desc(flagDefinition.createdAt),desc(flagDefinition.key)).limit(limit+1);const items=rows.slice(0,limit),last=items.at(-1);return{items,nextCursor:rows.length>limit&&last?Buffer.from(JSON.stringify([1,last.createdAt.toISOString(),last.key])).toString('base64url'):null}})}catch(error){throw safeFeatureFlagsError(error)}}
  async function listOverrides(db:FlagsDatabase,actor:FlagManagementActor,rawKey:string,input:{limit?:number,cursor?:string}={}){preflight(actor);const k=key(rawKey),{limit,tuple}=pagination(input,true);if(tuple&&tuple[4]!==k)throw new FeatureFlagsError('invalid-input');try{return await db.transaction(async tx=>{await guard(tx,actor,'list');const rows=await tx.select().from(flagOverride).where(and(eq(flagOverride.flagKey,k),tuple?or(lt(flagOverride.createdAt,new Date(tuple[1])),and(eq(flagOverride.createdAt,new Date(tuple[1])),or(lt(flagOverride.targetKind,tuple[2]),and(eq(flagOverride.targetKind,tuple[2]),lt(flagOverride.targetId,tuple[3]!))))):undefined)).orderBy(desc(flagOverride.createdAt),desc(flagOverride.targetKind),desc(flagOverride.targetId)).limit(limit+1);const items=rows.slice(0,limit),last=items.at(-1);return{items,nextCursor:rows.length>limit&&last?Buffer.from(JSON.stringify([1,last.createdAt.toISOString(),last.targetKind,last.targetId,k])).toString('base64url'):null}})}catch(error){throw safeFeatureFlagsError(error)}}
  return Object.freeze({evaluateMany,evaluateManyTx,evaluateBooleanDetails,evaluateBoolean,createDefinition,createDefinitionTx,updateDefinition,updateDefinitionTx,setOverride,removeOverride,setOverrideTx:(tx:FlagsConnection,actor:FlagManagementActor,k:string,expected:number,t:{targetKind:'user'|'tenant',targetId:string},value:boolean)=>overrideTx(tx,actor,k,expected,t,value),removeOverrideTx:(tx:FlagsConnection,actor:FlagManagementActor,k:string,expected:number,t:{targetKind:'user'|'tenant',targetId:string})=>overrideTx(tx,actor,k,expected,t,undefined),listDefinitions,listOverrides})
}
